### ISSUE TITLE
Update constraints to allow latest versions of the packages: `_fe_analyzer_shared` `analyzer` `dart_style`. 

### ISSUE THREAD

**Issue by water-mizuu** [rrousselGit/functional_widget#121]
As I was dealing with dependency constraints, it turns out that this package keeps the following packages from upgrading. The versions they are stuck in are:

`_fe_analyzer_shared`: 61.0.0
`analyzer`: 5.13.0
`dart_style`: 2.3.2

**Comment by yousefak007** [comment]
Because no versions of riverpod_lint match >2.3.7 <3.0.0 and riverpod_lint 2.3.7 depends on analyzer ^6.0.0, riverpod_lint ^2.3.7 requires analyzer ^6.0.0.
And because functional_widget >=0.10.1 depends on analyzer ^5.2.0, riverpod_lint ^2.3.7 is incompatible with functional_widget >=0.10.1.
So, because arabic_lang depends on both functional_widget ^0.10.1 and riverpod_lint ^2.3.7, version solving failed.

**Comment by yousefak007** [comment]
for now, I solve the problem by adding an analyzer to the dependency override

```yaml
dependency_overrides:
  analyzer: ^6.0.0
```

**Comment by rrousselGit** [comment]
Oh I haven't released the change. Let me do it.
